### ISSUE TITLE
injector code optimize

### ISSUE THREAD

**Issue by kuitos** [Brooooooklyn/angular1.x-injector#3]
I think there are some unnecessary code in your injector,my optimize version

``` typescript
return (target: any) => {
    let construct: any = function (args: any[]) {
      forEach(args, (arg, i) => target.prototype[deps[i]] = arg)
      return new target(args)
    }
    construct.$inject = <string[]>deps
    return construct
  }

```

I am not good at ts,so may be some mistake exist,but I think u know what I mean.

**Comment by Brooooooklyn** [comment]
thanks ~  good caught. 

And these codes would cause another problem. 
I fixed it via [cb52e16](https://github.com/Brooooooklyn/angular1.x-injector/commit/cb52e16d9db9e4d6423db8a0233d30b1dfc848ec)
